src/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/books');
});

Route::resource('books', BookController::class)->except(['create','show']);

Route::get('/books/{orderBy}', 'BookController@index')->name('books.sort');

Route::post('/books/search', 'BookController@search')->name('books.search');

Route::post('/books/export', 'BookController@export')->name('books.export');

src/app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'title', 'author'
    ];

    /**
     * One day it mays happen that we need to add more specific csv columns.
     * Like if the customer want to see the id or number etc... and are not selectable attributes
     */
    public static function csvColumns($selectedAttributes)
    {
        return $selectedAttributes;
    }

    public function exportCsv()
    {
        $csvArray = [];
        foreach ($this->attributes as $attribute) {
            $csvArray[] = $attribute;
        }

        return $csvArray;
    }

    public function exportXML()
    {
        $xmlBook = '<book>';
        foreach ($this->attributes as $key => $attribute) {
            $xmlBook .= '<' . $key . '>' . $attribute . '</' . $key . '>';
        }

        return $xmlBook . '</book>';
    }
}

src/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

src/app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the books.
     * And if there is a parameter 1 or 2 sort them by
     * Title and Author respectively
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $books = Book::all();

        if (isset($request->orderBy)) {
            if ($request->orderBy === '1') {
                $books = $books->sortBy('title');
            } else {
                $books = $books->sortBy('author');
            }
        }

        return view('books', compact('books'));
    }

    /**
     * Save the new book after validating the data
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:255',
            'author' => 'required|max:255',
        ]);

        Book::create($request->all());

        return redirect('/')->with('success', 'Book created successfully');
    }

    /**
     * Delete a book
     *
     * @param Book $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();

        return redirect('/')->with('success', 'Book deleted successfully');
    }

    /**
     * Update a book (author only)
     *
     * @param Request $request
     * @param Book $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $request->validate([
            'author' => 'required|max:255',
        ]);

        $book->author = $request->author;
        $book->save();

        return redirect('/')->with('success', 'Book updated successfully');
    }

    /**
     * Update a book (author only)
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $request->validate([
            'search' => 'max:255',
        ]);

        $books = Book::where('author', 'like', '%' . $request->search . '%')->get();
        $books2 = Book::where('title', 'like', '%' . $request->search . '%')->get();
        $books = $books->concat($books2);

        return view('books', compact('books'));
    }

    /**
     * Export the list of books
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function export(Request $request)
    {
        $request->validate([
            'type' => 'required|max:3',
        ]);

        $fileName = 'book';
        $selectedAttributes = [];

        if (isset($request->author) && $request->author) {
            $selectedAttributes[] = 'author';
        }

        if (isset($request->title) && $request->title) {
            $selectedAttributes[] = 'title';
        }

        if (empty($selectedAttributes)) {
            $books = Book::all();
            return redirect('books')
                ->withErrors(['error' => 'You didn\'t select any element of Book to export'])
                ->with('books', $books);
        }

        $books = Book::all($selectedAttributes);

        $export = '';
        switch ($request->type) {
            case 'csv':
                $fileName .= '.csv';
                return self::exportCSV($books, $fileName, $selectedAttributes);
                break;
            case 'xml':
                $fileName .= '.xml';
                return self::exportXML($books, $fileName);
                break;
        }
    }

    /**
     * Export a list of books to a csv file name with a filename.
     *
     * @param Array $books
     * @param String $fileName
     * @param Array $selectedAttributes
     *
     * @return \Illuminate\Http\Response
     */
    private static function exportCSV($books, $fileName, $selectedAttributes)
    {
        $headers = [
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0'
            , 'Content-type' => 'text/csv'
            , 'Content-Disposition' => 'attachment; filename=' . $fileName . '.csv'
            , 'Expires' => '0'
            , 'Pragma' => 'public',
        ];

        $callback = function () use ($books, $fileName, $selectedAttributes) {
            $fileHandler = fopen('php://output', 'w');

            fputcsv($fileHandler, Book::csvColumns($selectedAttributes));
            foreach ($books as $book) {
                fputcsv($fileHandler, $book->exportCsv());
            }

            fclose($fileHandler);
        };

        return response()->streamDownload($callback, $fileName, $headers);
    }

    /**
     * Export a list of books to a xml file name with a filename.
     *
     * @param Array $books
     * @param String $fileName
     *
     * @return \Illuminate\Http\Response
     */
    private static function exportXML($books, $fileName)
    {
        $headers = [
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0'
            , 'Content-type' => 'text/xml'
            , 'Content-Disposition' => 'attachment; filename=' . $fileName . '.xml'
            , 'Expires' => '0'
            , 'Pragma' => 'public',
        ];

        $callback = function () use ($books, $fileName) {
            $fileHandler = fopen('php://output', 'w');

            fputs($fileHandler, '<?xml version="1.0" encoding="UTF-8" ?>');
            fputs($fileHandler, '<books>');
            foreach ($books as $book) {
                fputs($fileHandler, $book->exportXML());
            }
            fputs($fileHandler, '</books>');
            fclose($fileHandler);
        };

        return response()->streamDownload($callback, $fileName, $headers);
    }
}

src/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

src/resources/views/books.blade.php
@extends('layouts.app')

@section('content')

    @include('common.errors')
    <!-- New Book Form -->
    <form action="{{ route('books.store') }}" method="POST">
    @csrf
    <div class="row mb-3">
        <label for="book" class="form-label">Book</label>
        <div class="col">
            <label for="book-title" class="form-label">Title</label>
            <input type="text" name="title" id="book-title" class="form-control">
        </div>
        <div class="col">
            <label for="book-author" class="form-label">Author</label>
            <input type="text" name="author" id="book-author" class="form-control">
        </div>
    </div>
    <div class="d-grid justify-content-md-end">
        <button type="submit" class="btn btn-outline-primary text-right">
        <i class="fas fa-book"></i> Add a book
        </button>
    </div>
    </form>
    <div>
        <form action="{{ route('books.export') }}" method="POST">
            @csrf
            <div class="row">
                <div class="col-1 mb-3">
                    <div class="form-check form-switch">
                        <input class="form-check-input"  name="title" type="checkbox" id="checkboxTitle" checked>
                        <label class="form-check-label" for="checkTitle">Title</label>
                    </div>
                    <div class="form-check form-switch">
                        <input class="form-check-input" name="author" type="checkbox" id="checkboxAuthor" checked>
                        <label class="form-check-label" for="checkboxAuthor">Author</label>
                    </div>
                </div>
                <div class="col-3 mb-3">
                        <button name="type"
                                value="csv"
                                alt="Download export csv"
                                class="btn btn-outline-primary"
                        >
                            <i class="fas fa-file-csv"></i> Export to CSV
                        </button>
                        <button name="type"
                                value="xml"
                                alt="Download export XML"
                                class="btn btn-outline-primary"
                        >
                            <i class="fas fa-file-excel"></i> Export to XML
                        </button>
                </div>
            </div>
        </form>
    </div>
    <div class="input-group d-grid justify-content-md-end">
        <form action="{{ route('books.search') }}" method="POST">
            @csrf
            <div class="input-group">
                <input  type="text"
                        name="search"
                        id="book-search"
                        class="form-control"
                        placeholder="Search"
                        >
                <button type="submit" class="btn btn-outline-primary text-right">
                    <i class="fas fa-search"></i> Search
                </button>
            </div>
        </form>
        <a href="{{ route('books.index') }}"
            alt="clean the research"
            class="btn btn-outline-primary text-right"
            >
                <i class="fas fa-redo"></i> Clean
        </a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td scope="col">
                    <a href="{{ route('books.sort', ['orderBy' => 1]) }}"
                        alt="order by title"
                        >
                        Title
                    </a>
                </td>
                <td scope="col">
                    <a href="{{ route('books.sort', ['orderBy' => 2]) }}"
                        alt="order by author"
                        >
                        Author
                    </a>
                </td>
                <td scope="col">
                    Delete
                </td>
            </tr>
        </thead>
        @if (isset($books))
        <tbody>
            @foreach($books as $book)
            <tr>
                <td>{{ $book->title }}</td>
                <td>
                    <form action="{{ route('books.update', $book->id) }}" method="POST" class="form-horizontal">
                        @method('PATCH')
                        @csrf
                        <div class="row">
                            <div class="col-sm-9">
                                <input value="{{ $book->author }}" name="author" id="book-author" class="form-control">
                            </div>
                            <div class="col-sm-3">
                                <button type="submit" class="btn btn-outline-secondary"><i class="fas fa-edit"></i></button>
                            </div>
                        </div>
                    </form>
                </td>
                <td>
                    <form action="{{ route('books.destroy', $book->id) }}" method="POST" class="form-horizontal">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
        @endif
    </table>
</div>

@endsection

src/resources/views/common/errors.blade.php
@if (count($errors) > 0)
    <!-- Form Error List -->
    <div class="alert alert-danger">
        <strong>Error, something happened</strong>

        <br><br>

        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

src/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="eng">
    <head>
        <title>Books List Assignment</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/books">Book assignment</a>
                </div>
            </nav>
        </div>
        <div class="container">
            @yield('content')
        </div>
        <!-- Javascript Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/c0a233aa9e.js" crossorigin="anonymous"></script>
    </body>
</html>